#!/usr/bin/env python3
"""
test_invoice_ocr.py — Milestone Zero: robust invoice ingestion (OCR fallback).

Verifies the three-tier extraction strategy WITHOUT the classification engine
(no ANTHROPIC_API_KEY needed): the deterministic extraction + confidence-gating
layer is what these tests pin down. analyze_item's flag logic is checked with a
stubbed engine so the gating behaviour is deterministic.

Fixtures are generated by tests/make_test_invoices.py. Run:
    python3 tests/make_test_invoices.py     # once, to (re)build fixtures
    python3 tests/test_invoice_ocr.py
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "server"))

import invoice_session as inv          # noqa: E402
import invoice_ocr as ocr              # noqa: E402

FIX = Path(__file__).resolve().parent / "fixtures"
PASS, FAIL = 0, 0


def check(name, cond, detail=""):
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"  PASS  {name}")
    else:
        FAIL += 1
        print(f"  FAIL  {name}   {detail}")


def main():
    if not ocr.tesseract_available():
        print("tesseract not available — cannot run OCR tests."); sys.exit(2)
    if not (FIX / "digital_invoice.pdf").exists():
        print("fixtures missing — run: python3 tests/make_test_invoices.py")
        sys.exit(2)

    # [1] Tier 1 — digital invoice unchanged (no regression)
    print("\n[1] Tier 1 — digital text-layer invoice")
    items, meta, status = inv.extract_with_fallback(str(FIX / "digital_invoice.pdf"))
    codes = {it["code"] for it in items}
    check("status == 'ok' (text layer used, OCR not invoked)", status == "ok", status)
    check("both line items found", len(items) == 2, str(len(items)))
    check("laptop code 8471300000 extracted", "8471300000" in codes, str(codes))
    check("chair code 9401300000 extracted", "9401300000" in codes, str(codes))

    # [2] Tier 2 — image-only invoice recovered by OCR
    print("\n[2] Tier 2 — image-only invoice (OCR)")
    items, meta, status = inv.extract_with_fallback(str(FIX / "image_invoice.pdf"))
    codes = {it["code"] for it in items}
    vals = {it["value"] for it in items}
    check("status == 'ocr_used'", status == "ocr_used", status)
    check("both line items recovered", len(items) == 2, str(len(items)))
    check("laptop code 8471.30.00 -> 84713000", "84713000" in codes, str(codes))
    check("chair code 9401.30.00 -> 94013000", "94013000" in codes, str(codes))
    check("value $13,120.00 recovered", any("13,120" in v for v in vals), str(vals))
    check("descriptions are non-empty",
          all(it["description"] for it in items), str([it["description"] for it in items]))

    # [3] Tier 2 — photographed CBP-7501-style form (looser alignment)
    print("\n[3] Tier 2 — CBP-7501-style form")
    items, meta, status = inv.extract_with_fallback(str(FIX / "form_scan.pdf"))
    check("status == 'ocr_used'", status == "ocr_used", status)
    check("one line item extracted", len(items) == 1, str(len(items)))
    if items:
        it = items[0]
        check("code 8302.42.3015 -> 8302423015", it["code"] == "8302423015", it["code"])
        check("description contains DRWRSLIDES",
              "DRWRSLIDES" in it["description"].upper().replace(" ", ""), it["description"])

    # [4] Tier 2.5 — per-field confidence gating on a smudged value
    print("\n[4] Tier 2.5 — per-field confidence gating")
    items, meta, status = inv.extract_with_fallback(str(FIX / "degraded.pdf"))
    check("status == 'ocr_used' (page still readable)", status == "ocr_used", status)
    check("page mean confidence stays high", meta.get("ocr_mean_conf", 0) >= 70,
          str(meta.get("ocr_mean_conf")))
    if items:
        it = items[0]
        check("sharp code NOT flagged low_confidence", "code" not in it["low_confidence"],
              str(it["low_confidence"]))
        check("smudged value IS flagged low_confidence", "value" in it["low_confidence"],
              str(it["low_confidence"]))
        check("value_conf is below threshold 70",
              it.get("value_conf") is not None and it["value_conf"] < ocr.CONF_THRESHOLD,
              str(it.get("value_conf")))

    # [5] Tier 3 — honest failure on a blank/unreadable scan
    print("\n[5] Tier 3 — honest failure")
    items, meta, status = inv.extract_with_fallback(str(FIX / "blank.pdf"))
    check("status == 'unreadable' (NOT a silent empty)", status == "unreadable", status)
    check("no items returned", items == [], str(items))
    result = inv.analyze_invoice(str(FIX / "blank.pdf"))
    check("analyze_invoice surfaces extraction_status='unreadable'",
          result.get("extraction_status") == "unreadable", str(result.get("extraction_status")))
    check("analyze_invoice carries a human message",
          "Couldn't read" in result.get("message", ""), result.get("message", ""))
    check("summary is NOT a bare 0/0/0 without status",
          result["summary"].get("extraction_status") == "unreadable",
          str(result["summary"]))

    # [6] _build_item code-uncertain branch (synthetic low-confidence code)
    #     Real dotted codes OCR robustly, so the mid-confidence code path is
    #     pinned with a constructed row rather than a blurred fixture.
    print("\n[6] Unit — low-confidence code marks the row uncertain")
    row = [
        {"text": "Steel", "conf": 92, "left": 40, "top": 100},
        {"text": "brackets", "conf": 91, "left": 140, "top": 100},
        {"text": "7308.90.00", "conf": 41, "left": 600, "top": 100},   # shaky code
        {"text": "$2,400.00", "conf": 95, "left": 900, "top": 100},
    ]
    it = ocr._build_item(row, None)
    check("low-confidence code is flagged", "code" in it["low_confidence"], str(it["low_confidence"]))
    check("code_uncertain is True", it["code_uncertain"] is True, str(it["code_uncertain"]))
    check("high-confidence value NOT flagged", "value" not in it["low_confidence"],
          str(it["low_confidence"]))

    # [7] analyze_item flag logic with a stubbed engine (no API key)
    print("\n[7] analyze_item — gating turns into the right flags")
    saved = inv.es.start

    def fake_start(desc, origin, hint):
        return {"status": "classified", "code": "7308900000", "defense": []}
    inv.es.start = fake_start
    try:
        # uncertain code -> LOW_CONFIDENCE_CODE, and NO false CODE_MISMATCH
        res = inv.analyze_item(
            {"row": 1, "description": "Steel brackets", "code": "",
             "value": "$2,400.00", "low_confidence": ["code"], "code_uncertain": True}, "CN")
        ftypes = {f["type"] for f in res["flags"]}
        check("uncertain code -> LOW_CONFIDENCE_CODE flag", "LOW_CONFIDENCE_CODE" in ftypes, str(ftypes))
        check("uncertain code -> no false CODE_MISMATCH", "CODE_MISMATCH" not in ftypes, str(ftypes))

        # shaky value -> LOW_CONFIDENCE_VALUE flag
        res = inv.analyze_item(
            {"row": 1, "description": "Steel brackets", "code": "7308900000",
             "value": "$2,400.00", "low_confidence": ["value"], "code_uncertain": False}, "CN")
        ftypes = {f["type"] for f in res["flags"]}
        check("shaky value -> LOW_CONFIDENCE_VALUE flag", "LOW_CONFIDENCE_VALUE" in ftypes, str(ftypes))
    finally:
        inv.es.start = saved

    print(f"\n{'='*50}\nRESULT: {PASS} passed, {FAIL} failed")
    sys.exit(1 if FAIL else 0)


if __name__ == "__main__":
    main()
