#!/usr/bin/env python3
"""
survey_api.py — Client-clarification survey routes for AImport Compliance.

Milestone One (V2), Sections 4–8. All routes are additive and registered on the
main app via include_router(); the existing classify/products/invoice routes are
untouched.

  POST /survey/create            broker -> create a survey from frozen lines
  GET  /survey/{token}           client -> the survey page (or expired/submitted)
  GET  /survey/{token}/data      client -> simplified, sanitised questions (JSON)
  POST /survey/{token}/submit    client -> answers; engine resumes per line
  GET  /survey/{token}/results   broker -> resolved + still-frozen lines (JSON)

Architectural guardrails enforced here:
  * option_set per question is always populated; the client never has a free-text
    path that yields a code directly.
  * The GRI state machine owns all sequencing on resume (engine_session.resume).
  * The oracle's only generative roles are (a) simplifying a question's wording,
    (b) selecting from an option set for supplementary free text. No code is ever
    generated by an LLM.
  * /survey/{token}/data never exposes codes, engine state, duty rates, or other
    clients' data — the client sees only their own line items.
"""
import sys
from pathlib import Path

from fastapi import APIRouter, Request
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import engine_session as es        # noqa: E402
import survey_db as sdb            # noqa: E402
import survey_text as stext        # noqa: E402
from survey_freeze import FREETEXT_OPTION, OCR_WRONG_OPTION  # noqa: E402

router = APIRouter()

# Options that, when chosen, reveal a single constrained free-text field.
_FREETEXT_TRIGGERS = {FREETEXT_OPTION, OCR_WRONG_OPTION}


# --------------------------------------------------------------------------- #
#  Models                                                                      #
# --------------------------------------------------------------------------- #

class FrozenLineIn(BaseModel):
    line_number: int = 0
    description_used: str | None = None
    hs_code_attempted: str | None = None
    freeze_reason: str = "NEEDS_DETAIL"
    engine_question: str = ""
    option_set: list = []
    engine_state_snapshot: dict = {}
    partial_heading: str | None = None


class SurveyCreateIn(BaseModel):
    session_broker_id: str = ""
    invoice_ref: str = ""
    frozen_lines: list[FrozenLineIn] = []
    client_email: str = ""
    language: str = "pl"          # client-facing survey language (Polish default)


class AnswerIn(BaseModel):
    question_id: str
    answer: str = ""
    answer_detail: str = ""


class SurveySubmitIn(BaseModel):
    answers: list[AnswerIn] = []
    client_email: str = ""


# --------------------------------------------------------------------------- #
#  Create (broker)                                                             #
# --------------------------------------------------------------------------- #

@router.post("/survey/create")
def survey_create(body: SurveyCreateIn, request: Request):
    frozen = [fl.model_dump() for fl in body.frozen_lines]
    if not frozen:
        return JSONResponse({"error": "No frozen lines — nothing to ask."},
                            status_code=400)
    created = sdb.create_session(
        broker_id=body.session_broker_id,
        invoice_ref=body.invoice_ref,
        frozen_lines=frozen,
        client_email=body.client_email,
        language=body.language or "pl",
    )
    token = created["token"]
    # Prefer the public base URL (hosted deployment) so the emailed link is
    # reachable by the client, not the broker's localhost.
    import os
    base = ((os.environ.get("PUBLIC_BASE_URL") or "").strip().rstrip("/")
            or str(request.base_url).rstrip("/"))
    return {"survey_token": token,
            "survey_url": f"{base}/survey/{token}"}


# --------------------------------------------------------------------------- #
#  Render (client)                                                             #
# --------------------------------------------------------------------------- #

@router.get("/survey/{token}")
def survey_page(token: str):
    sess = sdb.get_session(token)
    if sess is None or sess.get("expired"):
        return FileResponse(HERE / "survey_expired.html", status_code=404
                            if sess is None else 410)
    if sess.get("status") == "completed":
        return FileResponse(HERE / "survey_already_submitted.html")
    return FileResponse(HERE / "survey_form.html")


@router.get("/survey/{token}/data")
def survey_data(token: str):
    """Sanitised, client-facing question payload in the session's language
    (Polish by default). No codes, no engine state. The radio `value` the client
    submits stays the original (English) engine option; only the display label
    and context line are localised."""
    sess = sdb.get_session(token)
    if sess is None or sess.get("expired"):
        return JSONResponse({"status": "expired"}, status_code=410)
    if sess.get("status") == "completed":
        return JSONResponse({"status": "completed"})

    language = (sess.get("language") or "pl")
    questions = sdb.get_questions(token)
    total = len(questions)
    out = []
    for i, q in enumerate(questions, start=1):
        options = q["option_set"] or []
        out.append({
            "question_id": q["id"],
            "index": i,
            "total": total,
            "question": stext.simplify_question(q["engine_question"], language),
            # English option VALUES (submitted to the engine) ...
            "options": options,
            # ... and parallel localised display LABELS
            "option_labels": [stext.translate_option(o, language) for o in options],
            # which options open a single constrained free-text field
            "freetext_options": [o for o in options if o in _FREETEXT_TRIGGERS],
            "freeze_reason": q.get("freeze_reason"),
            "context_label": stext.freeze_reason_label(q.get("freeze_reason"), language),
        })
    return {"status": "pending", "total": total, "language": language,
            "intro": stext.survey_intro(language),
            "questions": out}


# --------------------------------------------------------------------------- #
#  Submit (client) — Section 8 resume                                          #
# --------------------------------------------------------------------------- #

@router.post("/survey/{token}/submit")
def survey_submit(token: str, body: SurveySubmitIn):
    sess = sdb.get_session(token)
    if sess is None:
        return JSONResponse({"error": "not found"}, status_code=404)
    if sess.get("expired"):
        return JSONResponse({"error": "expired"}, status_code=410)
    if sess.get("status") == "completed":
        return JSONResponse({"error": "already submitted"}, status_code=409)

    if body.client_email:
        sdb.set_client_email(token, body.client_email)

    resolved_any = False
    for a in body.answers:
        q = sdb.get_question(a.question_id)
        if not q or q["session_id"] != token:
            continue
        options = q["option_set"] or []
        answer = (a.answer or "").strip()
        detail = (a.answer_detail or "").strip()

        # GRI guardrail: the answer must be one of the engine's options, unless
        # it's a free-text-trigger option (which is itself in the option set).
        if answer and answer not in options:
            # tolerate an option the client typed verbatim differences-aside
            match = next((o for o in options if o.lower() == answer.lower()), None)
            answer = match or answer
        if answer not in options and not detail:
            # not a valid selection and no supplementary text -> leave frozen
            sdb.record_answer(q["id"], a.answer or "", detail)
            sdb.write_result(token, q["id"], q["line_number"], None, True,
                             "Answer was not one of the offered options.")
            continue

        sdb.record_answer(q["id"], answer, detail)
        final_code, still_frozen, notes = _resolve_question(q, answer, detail, market="EU")
        if not still_frozen:
            resolved_any = True
        sdb.write_result(token, q["id"], q["line_number"], final_code,
                         still_frozen, notes)

    sdb.mark_completed(token)

    # Optional broker notification (Section 4.4): plain text, no invoice data.
    notified = False
    if sess.get("client_email") or sess.get("broker_id"):
        notified = _notify_broker(sess, token)
    if notified:
        sdb.mark_notification_sent(token)

    return {"ok": True, "resolved_any": resolved_any}


def _resolve_question(q: dict, answer: str, detail: str, market="EU"):
    """Resume the GRI engine for one frozen line. Returns
    (final_code|None, still_frozen: bool, notes: str)."""
    snap = q["engine_state"] or {}
    kind = snap.get("kind")
    sig = snap.get("sig")

    try:
        if kind == "node":
            option_map = snap.get("option_map") or {}
            chosen_text = answer
            # Section 8.6: supplementary free text -> oracle picks an option.
            if detail and (answer in _FREETEXT_TRIGGERS or answer not in option_map):
                picked = stext.pick_option_for_freetext(
                    detail, list(option_map.keys()), market)
                if picked:
                    chosen_text = picked
            opt_id = option_map.get(chosen_text)
            if opt_id is None:
                return None, True, ("Needs manual review: the client's answer did "
                                    "not map to an engine option.")
            res = es.resume(snap, sig, opt_id)

        elif kind == "pre_classify":
            # The meaningful content is the supplementary description text.
            choice = detail or (answer if answer not in _FREETEXT_TRIGGERS else "")
            if not choice:
                return None, True, ("Needs manual review: client offered a photo / "
                                    "no description text was provided.")
            res = es.resume(snap, "__pre_classify__", choice)

        elif kind == "ocr_confirm":
            # Confirm or correct the unreadable field, then classify the line.
            confirmed = detail if answer == OCR_WRONG_OPTION else answer
            text = snap.get("text", "") or ""
            origin = snap.get("origin", "") or ""
            if not text.strip():
                return None, True, ("Needs manual review: confirmed value "
                                    f"'{confirmed}' but no description to classify.")
            res = es.start(text, origin, "")

        else:
            return None, True, "Needs manual review: unknown freeze type."
    except Exception as e:
        return None, True, f"Needs manual review: engine error ({str(e)[:80]})."

    status = res.get("status")
    if status == "classified":
        return res.get("code"), False, ""
    if status in ("needs_question", "needs_pre_classify"):
        second_q = res.get("question")
        if isinstance(second_q, dict):
            second_q = second_q.get("ask") or second_q.get("why") or "further detail"
        return None, True, f"Needs manual review: {second_q}"
    return None, True, (res.get("message") or "Needs manual review.")


def _notify_broker(sess: dict, token: str) -> bool:
    """Section 4.4 — a plain-text 'survey complete' notification with NO invoice
    data in the body. This milestone does not send mail from the backend
    (Section 10), so we only record intent and log; real delivery is a later
    milestone. Returns False (nothing actually sent) but is safe to call."""
    try:
        ref = sess.get("invoice_ref") or "your invoice"
        msg = f"Survey complete — {ref} is ready for review."
        import logging
        logging.getLogger("uvicorn.error").info("[survey] %s (token %s)",
                                                 msg, token[:8])
    except Exception:
        pass
    return False  # backend e-mail sending is intentionally out of scope here


# --------------------------------------------------------------------------- #
#  Results (broker)                                                            #
# --------------------------------------------------------------------------- #

@router.get("/survey/{token}/results")
def survey_results(token: str):
    sess = sdb.get_session(token)
    if sess is None:
        return JSONResponse({"error": "not found"}, status_code=404)
    questions = {q["id"]: q for q in sdb.get_questions(token)}
    results = sdb.get_results(token)
    lines = []
    for r in results:
        q = questions.get(r["question_id"], {})
        lines.append({
            "line_number": r["line_number"],
            "description": q.get("description_used"),
            "hs_code_attempted": q.get("hs_code_attempted"),
            "freeze_reason": q.get("freeze_reason"),
            "engine_question": q.get("engine_question"),
            "answer": q.get("answer"),
            "answer_detail": q.get("answer_detail"),
            "final_code": r["final_code"],
            "still_frozen": bool(r["still_frozen"]),
            "resolution_notes": r["resolution_notes"],
        })
    return {
        "token": token,
        "invoice_ref": sess.get("invoice_ref"),
        "broker_id": sess.get("broker_id"),
        "status": sess.get("status"),
        "created_at": sess.get("created_at"),
        "expires_at": sess.get("expires_at"),
        "expired": sess.get("expired"),
        "lines": lines,
    }


# --------------------------------------------------------------------------- #
#  Dashboard (broker)                                                          #
# --------------------------------------------------------------------------- #

class MarkSentIn(BaseModel):
    client_email: str = ""


@router.post("/survey/{token}/mark-sent")
def survey_mark_sent(token: str, body: MarkSentIn):
    """Record that the broker has sent the link (opened their mail client or
    copied it). Audit only — no mail is sent from the backend."""
    sess = sdb.get_session(token)
    if sess is None:
        return JSONResponse({"error": "not found"}, status_code=404)
    if body.client_email:
        sdb.set_client_email(token, body.client_email)
    sdb.mark_notification_sent(token)
    return {"ok": True}


@router.get("/survey/pending/list")
def survey_pending(broker_id: str = ""):
    return {"sessions": sdb.list_pending(broker_id)}
